// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/checkmarxDev/ast-sast-export/internal/app/metadata (interfaces: Provider)

// Package mock_app_metadata is a generated GoMock package.
package mock_app_metadata

import (
	reflect "reflect"

	metadata "github.com/checkmarxDev/ast-sast-export/internal/app/metadata"
	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetMetadataRecord mocks base method.
func (m *MockProvider) GetMetadataRecord(arg0 string, arg1 []*metadata.Query) (*metadata.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataRecord", arg0, arg1)
	ret0, _ := ret[0].(*metadata.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataRecord indicates an expected call of GetMetadataRecord.
func (mr *MockProviderMockRecorder) GetMetadataRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataRecord", reflect.TypeOf((*MockProvider)(nil).GetMetadataRecord), arg0, arg1)
}
