// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/checkmarxDev/ast-sast-export/internal/app/interfaces (interfaces: PresetProvider)
//
// Generated by this command:
//
//	mockgen -package mock_preset_interfaces -destination test/mocks/app/preset/mock_provider.go github.com/checkmarxDev/ast-sast-export/internal/app/interfaces PresetProvider
//
// Package mock_preset_interfaces is a generated GoMock package.
package mock_preset_interfaces

import (
	reflect "reflect"

	soap "github.com/checkmarxDev/ast-sast-export/internal/integration/soap"
	gomock "go.uber.org/mock/gomock"
)

// MockPresetProvider is a mock of PresetProvider interface.
type MockPresetProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPresetProviderMockRecorder
}

// MockPresetProviderMockRecorder is the mock recorder for MockPresetProvider.
type MockPresetProviderMockRecorder struct {
	mock *MockPresetProvider
}

// NewMockPresetProvider creates a new mock instance.
func NewMockPresetProvider(ctrl *gomock.Controller) *MockPresetProvider {
	mock := &MockPresetProvider{ctrl: ctrl}
	mock.recorder = &MockPresetProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresetProvider) EXPECT() *MockPresetProviderMockRecorder {
	return m.recorder
}

// GetPresetDetails mocks base method.
func (m *MockPresetProvider) GetPresetDetails(arg0 int) (*soap.GetPresetDetailsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresetDetails", arg0)
	ret0, _ := ret[0].(*soap.GetPresetDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresetDetails indicates an expected call of GetPresetDetails.
func (mr *MockPresetProviderMockRecorder) GetPresetDetails(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresetDetails", reflect.TypeOf((*MockPresetProvider)(nil).GetPresetDetails), arg0)
}
