name: Lint

on:
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: "v1.54.2"
          skip-go-installation: true
